# Import the os library
# This helps the program read values from the operating system (like API keys)
import os

# Import the OpenAI client library
# This library lets our system talk to OpenAI's AI models
from openai import OpenAI

# Import dotenv to load environment variables from the .env file
from dotenv import load_dotenv


# Load variables from the .env file into the system
# Usually the OpenAI API key is stored in this file
load_dotenv()


# Create an OpenAI client
# The API key is used to authenticate and connect to OpenAI servers
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))


# This function sends a prompt to the AI model
# and returns the response generated by the model
def generate_response(prompt: str) -> dict:
    try:

        # Send a request to the OpenAI model
        response = client.chat.completions.create(
            

            # Specify which AI model to use
            model="gpt-4o-mini",

            # Messages are sent in a conversation format
            messages=[

                # The system message defines the AI's role or behavior
                {"role": "system", "content": "You are an AI assistant."},

                # The user's input prompt that we want the AI to answer
                {"role": "user", "content": prompt}
            ],
            timeout= 10 # timeout control
        )

        # Return the text response generated by the AI model
        return {
            "content": response.choices[0].message.content,
            "usage": {
                "prompt_tokens": response.usage.prompt_tokens,
                "completion_tokens": response.usage.completion_tokens,
                "total_tokens": response.usage.total_tokens
            },
            "model": response.model
        }
    except Exception as e:
        # Fail-safe response (never break pipeline)
        return {
            "content": "AI service is temporarily unavailable.",
            "usage": {},
            "model": "error"
        }